# Generated by Django 5.0.4 on 2024-05-16 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0002_alter_babiesform_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babiesform',
            name='c_stay',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='day.categorystay'),
        ),
    ]
